# Generated by Django 6.0.6 on 2026-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
