# Generated by Django 6.0.6 on 2026-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_financialupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmetric',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financialmetric',
            name='month',
            field=models.CharField(default='', max_length=50),
        ),
    ]
