# Generated by Django 6.0.6 on 2026-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_financialmetric_budget_financialmetric_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmetric',
            name='month',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
