import { useEffect, useState, useCallback } from "react";
import { Box, Typography, Paper, Chip, Stack } from "@mui/material";
import DescriptionOutlinedIcon from "@mui/icons-material/DescriptionOutlined";

import { CardSkeletons, EmptyState, ErrorState } from "../../components/Common/StateViews";
import { getReports } from "../../api/reportsApi";

function formatDate(value) {
  if (!value) return "";
  return new Date(value).toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function Reports() {
  const [reports, setReports] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await getReports();
      setReports(res);
    } catch (err) {
      setError(err.response?.status || "network");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  return (
    <Box>
      <Typography variant="h4" mb={3}>Reports</Typography>

      {loading && <CardSkeletons count={3} />}
      {!loading && error && <ErrorState status={error} onRetry={fetchReports} />}

      {!loading && !error && (
        reports.length === 0 ? (
          <EmptyState
            title="No reports yet"
            subtitle="Reports generated by your agents will show up here."
          />
        ) : (
          <Stack spacing={2}>
            {reports.map((report) => (
              <Paper
                key={report.id}
                sx={{
                  p: { xs: 2, sm: 2.5 },
                  borderRadius: 3,
                  display: "flex",
                  gap: 2,
                  alignItems: "flex-start",
                }}
              >
                <Box
                  sx={{
                    width: 44,
                    height: 44,
                    borderRadius: 2,
                    bgcolor: "primary.main",
                    color: "#fff",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexShrink: 0,
                  }}
                >
                  <DescriptionOutlinedIcon />
                </Box>

                <Box sx={{ minWidth: 0, flexGrow: 1 }}>
                  <Stack
                    direction={{ xs: "column", sm: "row" }}
                    justifyContent="space-between"
                    alignItems={{ xs: "flex-start", sm: "center" }}
                    spacing={0.5}
                  >
                    <Chip size="small" label={report.report_type} color="primary" variant="outlined" />
                    <Typography variant="caption" color="text.secondary">
                      {formatDate(report.created_at)}
                    </Typography>
                  </Stack>
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    {report.summary}
                  </Typography>
                </Box>
              </Paper>
            ))}
          </Stack>
        )
      )}
    </Box>
  );
}